# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku
  # You may pin to the exact commit or the version.
  # uses: AkhileshNS/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
on:
  push:
    branches:
      - heroku-deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: AkhileshNS/heroku-deploy@v3.12.12
      - uses: actions/checkout@v2
        with:
    # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    # Email that you use with heroku
          heroku_email: mayesnbriana@gmail.com      
    # The appname to use for deploying/updating
          heroku_app_name: book-me-stripe-angular
    # The branch that you would like to deploy to Heroku
          branch: heroku-deployment
          appdir: byprieta 
