/* tslint: disable*/
// @ts-nocheck

const { writeFile, existSync, mkdirSync } = require('fs');
const { argv } = require("yargs");
require('dotenv').config({path: require('find-config')('.env')});
const environment = argv.enviornment;

//helper function to copy dynamically generated env vars
function writeFileUsingFS(targetPath, enviornmentFileContent) {
    writeFile(targetPath, enviornmentFileContent, function (err) {
        if(err) {
            console.log(err);
        }
        if (enviornmentFileContent !== '') {
            console.log(`wrote variables to ${targetPath}`);
        }
    });
}

//path to 'enviornments' directory
const envDirectory = '../environments';

if(!existSync(envDirectory)) {
    mkdirSync(envDirectory);
}

writeFileUsingFS(envDirectory + '/environment.prod.ts', '');
writeFileUsingFS(envDirectory + '/environment.ts', '');

// checks if in prod mode
const isProduction = environment === 'prod';

const apiUrl = "http://localhost:8000/";

const targetPath = isProduction
    ? envDirectory + '/environment.prod.ts'
    : envDirectory + '/enviroment.ts';


const enviornmentFileContent = `
    // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
    
    export const environment = {
        production: ${isProduction},
        apiUrl: '${apiUrl}',
        stripeKey: '${process.env.STRIPE_SECRET_KEY}'
    };
    `;

    writeFileUsingFS(targetPath, enviornmentFileContent);

/*tslint:enable */